repos:
  - repo: local
    hooks:
      - id: pytest-cov
        name: Run pytest + coverage
        entry: pytest --cov=app/src/ --cov-branch --cov-fail-under=80 app/tests
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: pylint
        name: Run pylint
        entry: pylint app/src/
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: bandit
        name: Run bandit security
        entry: bandit -r app/src/
        language: system
        pass_filenames: false
